{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.901.0 (24.07)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"SortItems\",\"SortCategory\",\"SortSector\",\"Fin CFO Dashboard\",\"SortCategory 2\",\"File and Date\",\"Fin Ratio 2023\",\"Sort Ratio Items\",\"type of inv sort\",\"Legal - Major Legal Exposure\",\"Project Team - Project Delivery\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "5a093866-b3c0-45f7-878c-a658aedaea84",
        "fromColumn": "Date",
        "fromTable": "File and Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f505174c-9f82-45f9-bd3a-f7df7facc40c"
      },
      {
        "name": "6768986f-42e9-41a6-a4b5-fe88f025620f",
        "fromColumn": "Category",
        "fromTable": "Fin CFO Dashboard",
        "toColumn": "Category",
        "toTable": "SortCategory"
      },
      {
        "name": "f60e4fa9-1119-4f7d-9872-a9fb71535720",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Sector",
        "fromTable": "Fin CFO Dashboard",
        "toColumn": "Sector",
        "toTable": "SortSector"
      },
      {
        "name": "b379909e-159e-4095-a917-bf085c5c140a",
        "fromColumn": "Items",
        "fromTable": "Fin CFO Dashboard",
        "toColumn": "Items",
        "toTable": "SortItems"
      },
      {
        "name": "69c183b0-04da-4daa-8bb2-b0ac6448270a",
        "fromColumn": "Report Date",
        "fromTable": "Calendar Fin CFO",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_dbdee00c-5d5c-45f1-b3fd-cbe498e48cff"
      },
      {
        "name": "efde6668-caac-41b7-bcb1-e7641c4052e1",
        "fromColumn": "Report Date",
        "fromTable": "Fin CFO Dashboard",
        "toColumn": "Report Date",
        "toTable": "Calendar Fin CFO"
      },
      {
        "name": "40eb1b4e-ab8f-45d9-8f3d-dab5a41ecf80",
        "fromColumn": "Report Date",
        "fromTable": "Fin Ratio 2023",
        "toColumn": "Report Date",
        "toTable": "Calendar Fin CFO"
      },
      {
        "name": "ac9d055d-2f9c-4604-a8d0-ed566a0245c8",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Items",
        "fromTable": "Fin Ratio 2023",
        "toColumn": "Items",
        "toTable": "Sort Ratio Items"
      },
      {
        "name": "8b1d6346-a41d-46ca-8570-54f30b04a3d6",
        "fromColumn": "Next Hearing Date",
        "fromTable": "Legal - Major Legal Exposure",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f554ce51-35a6-4445-a2f3-e881cb9da01b"
      },
      {
        "name": "f66dcef3-e510-4e5e-b7a6-20d2e3b21deb",
        "fromColumn": "Target COD",
        "fromTable": "Project Team - Project Delivery",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6c532078-52c3-4050-9403-1e5586b77d25"
      },
      {
        "name": "7ab08032-3a88-4ec6-b11b-a520b6d9d153",
        "fromColumn": "Revised COD",
        "fromTable": "Project Team - Project Delivery",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bdb843d8-8cdb-4dd9-aa55-7b0619d863a5"
      },
      {
        "name": "ce0eb82b-f3d7-4488-bc81-b265b40e2f9f",
        "fromColumn": "Date Case Filed",
        "fromTable": "Legal - Major Legal Exposure",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e3c4b969-af3e-4562-9aca-fd58fbf576de"
      },
      {
        "name": "b01202db-02ae-4f58-a0fc-5e6eb292ad8c",
        "fromColumn": "Notice to Proceed",
        "fromTable": "Project Team - Project Delivery",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4c8fda47-6501-4a3e-bdc4-012ddbbd5524"
      }
    ],
    "sourceQueryCulture": "en-MY",
    "tables": [
      {
        "name": "DateTableTemplate_c45c6369-368d-4630-86a7-a45f445d38bc",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3881a4c6-a8e9-4a63-8f43-e8034a66d9ce",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "74268b41-ef80-46ea-b13e-8c93eb0b4511",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8010c2b1-4750-4aa3-8962-765d59eefdf7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "dd6e04cf-7941-4f20-950d-4023fee13ba2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ecd14e7f-bde3-4142-b3f2-c0b0c6144fec",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "de48e278-cfe0-4645-bccb-8d1cc5ea83b1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4d1669a1-c04f-4340-a06a-d0660053a6a4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f0570d36-e527-4db6-94d9-0559e3c3a2a0",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f9d505d6-994b-4128-b3d5-93f525d860a8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b1542a54-c57b-462d-9a50-dc8bef6b1793",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f0894bf0-98a0-451d-bfff-56647e2d54fc",
                "ordinal": 3
              }
            ],
            "lineageTag": "78bbd023-42e7-4af2-bbf5-598f62451713"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "5f686ec0-8c5f-4006-ae02-f9745fd966cb",
        "partitions": [
          {
            "name": "DateTableTemplate_c45c6369-368d-4630-86a7-a45f445d38bc-650fc473-642c-43b5-851d-5fbf51180450",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Measure",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "fc51d36aa06c4d2bbb98c2a20c6d9e17"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "875afa57-9830-4d7f-a96b-b50fb6d0b662",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "70f9a7db-c21a-4735-9c11-55a6f02d9a3e",
        "measures": [
          {
            "name": "Dynamic Count",
            "displayFolder": "Dynamic Titles",
            "expression": "CALCULATE(COUNTROWS(FILTER('Fin CFO Dashboard', 'Fin CFO Dashboard'[Budget YTD/31 - 60 Days] > 'Fin CFO Dashboard'[Actual YTD/< 30 Days])), 'Fin CFO Dashboard'[Items] = \"Revenue\") ",
            "formatString": "0",
            "lineageTag": "6103e05f-dbc8-433b-aaa4-66af0b086b9c"
          },
          {
            "name": "GearingRatio",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Cashflow",
            "expression": [
              "IF(ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "DIVIDE(CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), 'Fin CFO Dashboard'[Items] = \"Total Borrowings\"), CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), 'Fin CFO Dashboard'[Items] = \"Shareholder's Fund\"), 0),",
              "DIVIDE(CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), 'Fin CFO Dashboard'[Items] = \"Total Borrowings\", 'Fin CFO Dashboard'[Entity] = \"Group\"), CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), 'Fin CFO Dashboard'[Items] = \"Shareholder's Fund\", 'Fin CFO Dashboard'[Entity] = \"Group\"), 0) )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "2b89d0c4-d5ea-41ee-a52c-b4fb79d8d293"
          },
          {
            "name": "<30Days",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Receivables & Payables",
            "expression": [
              "IF(ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date])),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), 'Fin CFO Dashboard'[Entity] = \"Group\", 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date])))"
            ],
            "lineageTag": "f0b4e8d8-125c-46d0-a3a9-6b6782151151"
          },
          {
            "name": "31-60Days",
            "displayFolder": "Receivables & Payables",
            "expression": [
              "IF(ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Budget YTD/31 - 60 Days]), 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date])),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Budget YTD/31 - 60 Days]), 'Fin CFO Dashboard'[Entity] = \"Group\", 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date])))"
            ],
            "formatString": "0",
            "lineageTag": "b580da4c-e4fa-4b5c-b64c-9285acd84488"
          },
          {
            "name": "61-90Days",
            "displayFolder": "Receivables & Payables",
            "expression": [
              "IF(ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Current Year Budget/61 - 90 Days]), 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date])),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Current Year Budget/61 - 90 Days]), 'Fin CFO Dashboard'[Entity] = \"Group\", 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date])))"
            ],
            "formatString": "0",
            "lineageTag": "3e7652b6-88e0-4e1a-b440-538ffdaa5e5b"
          },
          {
            "name": "91-365Days",
            "displayFolder": "Receivables & Payables",
            "expression": [
              "IF(ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Next Year Budget/91 - 365 Days]), 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date])),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Next Year Budget/91 - 365 Days]), 'Fin CFO Dashboard'[Entity] = \"Group\", 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date])))"
            ],
            "formatString": "0",
            "lineageTag": "b590acd9-6917-4ba5-8999-d776b46ab2d1"
          },
          {
            "name": ">365Days",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Receivables & Payables",
            "expression": [
              "IF(ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Previous Year Actual/> 365 Days]), 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date])),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Previous Year Actual/> 365 Days]), 'Fin CFO Dashboard'[Entity] = \"Group\", 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date])))"
            ],
            "lineageTag": "7acf0cbc-8dcb-43af-a99e-938e3f203af8"
          },
          {
            "name": "Var",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Matrix",
            "expression": "DIVIDE(CALCULATE([Actual CY Matrix]-[Budget YTD CY Matrix]),CALCULATE([Budget YTD CY Matrix]))*100",
            "formatString": "0.0",
            "lineageTag": "98886278-c450-4674-98ae-c1156b91d4bb"
          },
          {
            "name": "Actual PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Matrix",
            "expression": [
              "IF(ISFILTERED(SortItems[Items]),",
              "    CALCULATE(SUM('Fin CFO Dashboard'[Previous Year Actual/> 365 Days] )/1000, 'Fin CFO Dashboard'[Report Date] = MAX('Fin CFO Dashboard'[Report Date])),",
              "    CALCULATE(SUM('Fin CFO Dashboard'[Previous Year Actual/> 365 Days] )/1000, 'Fin CFO Dashboard'[Report Date] = MAX('Fin CFO Dashboard'[Report Date]), 'Fin CFO Dashboard'[Items] = \"Revenue\"))"
            ],
            "formatString": "#,0",
            "lineageTag": "5f04b6e0-5ac2-4587-8330-2cc69276b992"
          },
          {
            "name": "Actual CY Matrix",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Matrix",
            "expression": [
              "IF(ISFILTERED(SortItems[Items]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days] )/1000, 'Fin CFO Dashboard'[Report Date] = MAX('Fin CFO Dashboard'[Report Date])),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days] )/1000, 'Fin CFO Dashboard'[Report Date] = MAX('Fin CFO Dashboard'[Report Date]), 'Fin CFO Dashboard'[Items] = \"Revenue\"))"
            ],
            "formatString": "#,0",
            "lineageTag": "df0c3d44-afc0-457a-85c0-dcce28878b32"
          },
          {
            "name": "YoY%",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Matrix",
            "expression": "DIVIDE([Diff],[Actual PY]) * 100 ",
            "formatString": "0.0",
            "lineageTag": "025a514f-b0db-4e15-8928-dad3a9af514f"
          },
          {
            "name": "Budget YTD CY",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "KPI",
            "expression": [
              "IF(ISFILTERED(SortItems[Items]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Budget YTD/31 - 60 Days] ), 'Fin CFO Dashboard'[Report Date] = MAX('Fin CFO Dashboard'[Report Date])),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Budget YTD/31 - 60 Days] ), 'Fin CFO Dashboard'[Report Date] = MAX('Fin CFO Dashboard'[Report Date]), 'Fin CFO Dashboard'[Items] = \"Revenue\"))"
            ],
            "formatString": "#,0",
            "lineageTag": "ea0231d2-b2d6-4ff2-a679-e34ff1718e41"
          },
          {
            "name": "Diff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Matrix",
            "expression": "[Actual CY Matrix] - [Actual PY]",
            "lineageTag": "8ab29e59-232b-42e3-9ca4-91ce9d2bb105"
          },
          {
            "name": "TotalRevenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Matrix",
            "expression": "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), 'Fin CFO Dashboard'[Items] = \"Revenue\", LASTDATE('Fin CFO Dashboard'[Report Date]))",
            "lineageTag": "d6a17f2d-e868-4851-9133-2986dd803414"
          },
          {
            "name": "Actual CY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "KPI",
            "expression": [
              "IF(ISFILTERED(SortItems[Items]), ",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days] ), 'Fin CFO Dashboard'[Report Date] = MAX('Fin CFO Dashboard'[Report Date])),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days] ), 'Fin CFO Dashboard'[Report Date] = MAX('Fin CFO Dashboard'[Report Date]), 'Fin CFO Dashboard'[Items] = \"Revenue\"))"
            ],
            "lineageTag": "b5e942c3-72c5-45c7-bb24-0f63dd780b00"
          },
          {
            "name": "SectoralCompo",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Matrix",
            "expression": [
              "IF(ISFILTERED(SortItems[Items]),",
              "DIVIDE([Actual CY Matrix], CALCULATE([Actual CY Matrix], ALLSELECTED('Fin CFO Dashboard')),0),",
              "CALCULATE(DIVIDE([Actual CY Matrix], CALCULATE([Actual CY Matrix], ALLSELECTED('Fin CFO Dashboard')),0), 'Fin CFO Dashboard'[Items] = \"Revenue\"))"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "673d596c-df3e-49a6-b7ad-b484765d6d8d"
          },
          {
            "name": "Actual PY KPI",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "KPI",
            "expression": [
              "IF(ISFILTERED(SortItems[Items]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Previous Year Actual/> 365 Days])),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Previous Year Actual/> 365 Days]), 'Fin CFO Dashboard'[Items] = \"Revenue\"))"
            ],
            "lineageTag": "df9df178-224e-4cc0-a7cd-ae5fd8345974"
          },
          {
            "name": "ActualCY Cash",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Cashflow",
            "expression": [
              "IF(ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), LASTDATE('Fin CFO Dashboard'[Report Date]))/1000,",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), LASTDATE('Fin CFO Dashboard'[Report Date]), 'Fin CFO Dashboard'[Entity] = \"Group\")/1000)"
            ],
            "formatString": "#,0",
            "lineageTag": "d4794cdb-4f72-4030-b32f-052dcbab83e7"
          },
          {
            "name": "SelectedDate",
            "displayFolder": "Dynamic Titles",
            "expression": "SELECTEDVALUE('Calendar Fin CFO'[Month], FORMAT(LASTDATE('Calendar Fin CFO'[Report Date]), \"mmm\")) & \" | \" & SELECTEDVALUE('Calendar Fin CFO'[Year], FORMAT(LASTDATE('Calendar Fin CFO'[Report Date]), \"yyyy\"))",
            "lineageTag": "60e8257d-51cd-48f8-a496-6f7d063a4768"
          },
          {
            "name": "ActualPY Cash",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cashflow",
            "expression": "IF(CALCULATE([ActualCY Cash], SAMEPERIODLASTYEAR('Fin CFO Dashboard'[Report Date])) = BLANK(), 0, CALCULATE([ActualCY Cash], SAMEPERIODLASTYEAR('Fin CFO Dashboard'[Report Date]))  )",
            "lineageTag": "4a3a1b2b-237d-4118-af17-bfadb50a023f"
          },
          {
            "name": "ActualLM Cash",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Cashflow",
            "expression": [
              "IF(ISFILTERED('Fin CFO Dashboard'[Entity]),    ",
              "IF(CALCULATE([ActualCY Cash], DATEADD('Fin CFO Dashboard'[Report Date], -1, MONTH)) = BLANK(), 0, CALCULATE([ActualCY Cash], DATEADD('Fin CFO Dashboard'[Report Date], -1, MONTH))),",
              "IF(CALCULATE([ActualCY Cash], DATEADD('Fin CFO Dashboard'[Report Date], -1, MONTH), 'Fin CFO Dashboard'[Entity]= \"Group\") = BLANK(), 0, CALCULATE([ActualCY Cash], DATEADD('Fin CFO Dashboard'[Report Date], -1, MONTH), 'Fin CFO Dashboard'[Entity] = \"Group\")))"
            ],
            "formatString": "#,0",
            "lineageTag": "3485d222-3c1b-4898-8d64-54bc326e88bc"
          },
          {
            "name": "VarMonth",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Cashflow",
            "expression": "DIVIDE(CALCULATE([ActualCY Cash]-[ActualLM Cash]), [ActualLM Cash], 0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "65eb0e19-a242-446a-98be-ae6c526cfe61"
          },
          {
            "name": "BudgetedCY Cash",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Cashflow",
            "expression": [
              "IF(ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Budget YTD/31 - 60 Days]), LASTDATE('Fin CFO Dashboard'[Report Date]))/1000,",
              "CALCULATE(SUM('Fin CFO Dashboard'[Budget YTD/31 - 60 Days]), LASTDATE('Fin CFO Dashboard'[Report Date]), 'Fin CFO Dashboard'[Entity] = \"Group\")/1000)"
            ],
            "formatString": "#,0",
            "lineageTag": "9996d4e3-b9a4-4bab-837c-3c7567b05568"
          },
          {
            "name": "VarBudget",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Cashflow",
            "expression": "DIVIDE(CALCULATE([ActualCY Cash]-[BudgetedCY Cash]), [BudgetedCY Cash], 0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "9136dcac-5fb3-4e98-b4af-01470ed67c9c"
          },
          {
            "name": "TotalCash",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Cashflow",
            "expression": [
              "IF(ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), LASTDATE('Fin CFO Dashboard'[Report Date]), 'Fin CFO Dashboard'[Items] = \"Cash and Cash Equivalents\"),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), LASTDATE('Fin CFO Dashboard'[Report Date]), 'Fin CFO Dashboard'[Items] = \"Cash and Cash Equivalents\", 'Fin CFO Dashboard'[Entity] = \"Group\"))"
            ],
            "formatString": "#,0",
            "lineageTag": "734c5fd9-fa0a-43d8-83b4-810f9f43b31f"
          },
          {
            "name": "TotalBorrowings",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Cashflow",
            "expression": [
              "IF(ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), LASTDATE('Fin CFO Dashboard'[Report Date]), 'Fin CFO Dashboard'[Items] = \"Total Borrowings\"),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), LASTDATE('Fin CFO Dashboard'[Report Date]), 'Fin CFO Dashboard'[Items] = \"Total Borrowings\", 'Fin CFO Dashboard'[Entity] = \"Group\"))"
            ],
            "formatString": "#,0",
            "lineageTag": "5c7a906f-a5ec-4faa-85d3-d64c9f64ef94"
          },
          {
            "name": "NetDebt",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cashflow",
            "expression": "[TotalBorrowings All]-[TotalCash All]",
            "lineageTag": "bd4d5415-0e24-462a-982f-6ae86ca087c5"
          },
          {
            "name": "TotalCash All",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cashflow",
            "expression": [
              "IF(ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), 'Fin CFO Dashboard'[Items] = \"Cash and Cash Equivalents\"),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), 'Fin CFO Dashboard'[Items] = \"Cash and Cash Equivalents\", 'Fin CFO Dashboard'[Entity] = \"Group\"))"
            ],
            "lineageTag": "949e167d-bbee-4775-b4b4-eaa3b3f3039e"
          },
          {
            "name": "TotalBorrowings All",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cashflow",
            "expression": [
              "IF(ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), 'Fin CFO Dashboard'[Items] = \"Total Borrowings\"),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), 'Fin CFO Dashboard'[Items] = \"Total Borrowings\", 'Fin CFO Dashboard'[Entity] = \"Group\"))"
            ],
            "lineageTag": "fdacd64e-a1a5-477d-b34a-6ebea2fadfc9"
          },
          {
            "name": "Shareholder's Fund",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Cashflow",
            "expression": [
              "IF(ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), 'Fin CFO Dashboard'[Items] = \"Total equity\", LASTDATE('Fin CFO Dashboard'[Report Date])),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), 'Fin CFO Dashboard'[Items] = \"Total equity\", LASTDATE('Fin CFO Dashboard'[Report Date]), 'Fin CFO Dashboard'[Entity] = \"Group\"))"
            ],
            "formatString": "#,0",
            "lineageTag": "466db5b5-1c7c-48c4-b327-c096709b436a"
          },
          {
            "name": "Budget YTD CY Matrix",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Matrix",
            "expression": [
              "IF(ISFILTERED(SortItems[Items]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Budget YTD/31 - 60 Days] )/1000, 'Fin CFO Dashboard'[Report Date] = MAX('Fin CFO Dashboard'[Report Date])),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Budget YTD/31 - 60 Days] )/1000, 'Fin CFO Dashboard'[Report Date] = MAX('Fin CFO Dashboard'[Report Date]), 'Fin CFO Dashboard'[Items] = \"Revenue\"))"
            ],
            "formatString": "#,0",
            "lineageTag": "49a52018-98c9-4a8b-8f7a-ed9d80b26a31"
          },
          {
            "name": "SumReceivables",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Receivables & Payables",
            "expression": [
              "SWITCH(TRUE(),",
              "ISFILTERED(Aging),",
              "SWITCH(MAX(Aging[Aging]),",
              "\"< 30 Days\", CALCULATE([<30Days], 'Fin CFO Dashboard'[Category] = \"Receivables\"),",
              "\"31-60 Days\", CALCULATE([31-60Days], 'Fin CFO Dashboard'[Category] = \"Receivables\"),",
              "\"61-90 Days\", CALCULATE([61-90Days], 'Fin CFO Dashboard'[Category] = \"Receivables\"),",
              "\"91-365 Days\", CALCULATE([91-365Days], 'Fin CFO Dashboard'[Category] = \"Receivables\"),",
              "\"> 365 Days\", CALCULATE([>365Days], 'Fin CFO Dashboard'[Category] = \"Receivables\")),",
              "ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Total Aging]), 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date]), 'Fin CFO Dashboard'[Category] = \"Receivables\"),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Total Aging]), 'Fin CFO Dashboard'[Entity] = \"Group\", 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date]), 'Fin CFO Dashboard'[Category] = \"Receivables\"))"
            ],
            "lineageTag": "53d1212b-0188-4ef0-8e59-3d3796a92885"
          },
          {
            "name": "SumOtherPayables",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Receivables & Payables",
            "expression": [
              "SWITCH(TRUE(),",
              "ISFILTERED(Aging),",
              "SWITCH(MAX(Aging[Aging]),",
              "\"< 30 Days\", CALCULATE([<30Days], 'Fin CFO Dashboard'[Category] = \"Other Payables\"),",
              "\"31-60 Days\", CALCULATE([31-60Days], 'Fin CFO Dashboard'[Category] = \"Other Payables\"),",
              "\"61-90 Days\", CALCULATE([61-90Days], 'Fin CFO Dashboard'[Category] = \"Other Payables\"),",
              "\"91-365 Days\", CALCULATE([91-365Days], 'Fin CFO Dashboard'[Category] = \"Other Payables\"),",
              "\"> 365 Days\", CALCULATE([>365Days], 'Fin CFO Dashboard'[Category] = \"Other Payables\")),",
              "ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Total Aging]), 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date]), 'Fin CFO Dashboard'[Category] = \"Other Payables\"),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Total Aging]), 'Fin CFO Dashboard'[Entity] = \"Group\", 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date]), 'Fin CFO Dashboard'[Category] = \"Other Payables\"))"
            ],
            "lineageTag": "94709bf4-e523-412c-b779-169aeb4ee4ae"
          },
          {
            "name": "SumTradePayables",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Receivables & Payables",
            "expression": [
              "SWITCH(TRUE(),",
              "ISFILTERED(Aging),",
              "SWITCH(MAX(Aging[Aging]),",
              "\"< 30 Days\", CALCULATE([<30Days], 'Fin CFO Dashboard'[Category] = \"Trade Payables YTD\"),",
              "\"31-60 Days\", CALCULATE([31-60Days], 'Fin CFO Dashboard'[Category] = \"Trade Payables YTD\"),",
              "\"61-90 Days\", CALCULATE([61-90Days], 'Fin CFO Dashboard'[Category] = \"Trade Payables YTD\"),",
              "\"91-365 Days\", CALCULATE([91-365Days], 'Fin CFO Dashboard'[Category] = \"Trade Payables YTD\"),",
              "\"> 365 Days\", CALCULATE([>365Days], 'Fin CFO Dashboard'[Category] = \"Trade Payables YTD\")),",
              "ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Total Aging]), 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date]), 'Fin CFO Dashboard'[Category] = \"Trade Payables YTD\"),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Total Aging]), 'Fin CFO Dashboard'[Entity] = \"Group\", 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date]), 'Fin CFO Dashboard'[Category] = \"Trade Payables YTD\"))"
            ],
            "lineageTag": "285dbb0e-d5fc-4463-88b0-763a766d4f35"
          },
          {
            "name": "SumAging",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Receivables & Payables",
            "expression": [
              "SWITCH(TRUE(),",
              "ISFILTERED(Aging),",
              "SWITCH(MAX(Aging[Aging]),",
              "\"< 30 Days\", [<30Days],",
              "\"31-60 Days\", [31-60Days],",
              "\"61-90 Days\", [61-90Days],",
              "\"91-365 Days\", [91-365Days],",
              "\"> 365 Days\", [>365Days]),",
              "ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Total Aging]), 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date])),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Total Aging]), 'Fin CFO Dashboard'[Entity] = \"Group\", 'Fin CFO Dashboard'[Report Date] = MAX('Calendar Fin CFO'[Report Date]))) "
            ],
            "lineageTag": "80d24b69-581c-457f-90d6-186ee80f3412"
          },
          {
            "name": "YTD RM Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Statements RM",
            "expression": "CALCULATE(SUM('Fin Ratio 2023'[Value]), 'Fin Ratio 2023'[Report Date] = MAX('Fin Ratio 2023'[Report Date]), 'Fin Ratio 2023'[Attribute] = \"Actual YTD Group\" || 'Fin Ratio 2023'[Attribute] = \"Actual YTD Company\")",
            "formatString": "#,0",
            "lineageTag": "31290a33-727c-4f1b-b0b6-7323ae28e4e1"
          },
          {
            "name": "Times Values",
            "displayFolder": "Statements Times",
            "expression": "CALCULATE(SUM('Fin Ratio 2023'[Value]), 'Fin Ratio 2023'[Report Date] = MAX('Fin Ratio 2023'[Report Date]), 'Fin Ratio 2023'[Attribute] = \"Actual YTD Group\" || 'Fin Ratio 2023'[Attribute] = \"Actual YTD Company\")",
            "formatString": "0.00",
            "lineageTag": "186e0718-a2c4-4ac9-a1c3-f6a1484fd432"
          },
          {
            "name": "% Value",
            "displayFolder": "Statements %",
            "expression": "CALCULATE(SUM('Fin Ratio 2023'[Value]), 'Fin Ratio 2023'[Report Date] = MAX('Fin Ratio 2023'[Report Date]), 'Fin Ratio 2023'[Attribute] = \"Actual YTD Group\" || 'Fin Ratio 2023'[Attribute] = \"Actual YTD Company\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "e83fd6c7-f308-46bc-be55-d8215b7d05ba"
          },
          {
            "name": "2022 RM Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Statements RM",
            "expression": "CALCULATE(SUM('Fin Ratio 2023'[Value]), 'Fin Ratio 2023'[Report Date] = MAX('Fin Ratio 2023'[Report Date]), 'Fin Ratio 2023'[Attribute] = \"2022 Actual Group\" || 'Fin Ratio 2023'[Attribute] = \"2022 Actual Company\")",
            "formatString": "#,0",
            "lineageTag": "9c291ae8-e8b0-46f4-abf1-d87a74223912"
          },
          {
            "name": "2021 RM Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Statements RM",
            "expression": "CALCULATE(SUM('Fin Ratio 2023'[Value]), 'Fin Ratio 2023'[Report Date] = MAX('Fin Ratio 2023'[Report Date]), 'Fin Ratio 2023'[Attribute] = \"2021 Actual Group\" || 'Fin Ratio 2023'[Attribute] = \"2021 Actual Company\")",
            "formatString": "#,0",
            "lineageTag": "d0c4660b-d39a-49e8-9466-590e03342c7a"
          },
          {
            "name": "2022 Times Value",
            "displayFolder": "Statements Times",
            "expression": "CALCULATE(SUM('Fin Ratio 2023'[Value]), 'Fin Ratio 2023'[Report Date] = MAX('Fin Ratio 2023'[Report Date]), 'Fin Ratio 2023'[Attribute] = \"2022 Actual Group\" || 'Fin Ratio 2023'[Attribute] = \"2022 Actual Company\")",
            "formatString": "0.00",
            "lineageTag": "2b2387a2-a775-4e4f-9ee4-2ef3d2cd9355"
          },
          {
            "name": "2022 % Value",
            "displayFolder": "Statements %",
            "expression": "CALCULATE(SUM('Fin Ratio 2023'[Value]), 'Fin Ratio 2023'[Report Date] = MAX('Fin Ratio 2023'[Report Date]), 'Fin Ratio 2023'[Attribute] = \"2022 Actual Group\" || 'Fin Ratio 2023'[Attribute] = \"2022 Actual Company\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "fe466a43-d255-4434-b78a-f7df1b2dbd29"
          },
          {
            "name": "2021 Times Value",
            "displayFolder": "Statements Times",
            "expression": "CALCULATE(SUM('Fin Ratio 2023'[Value]), 'Fin Ratio 2023'[Report Date] = MAX('Fin Ratio 2023'[Report Date]), 'Fin Ratio 2023'[Attribute] = \"2021 Actual Group\" || 'Fin Ratio 2023'[Attribute] = \"2021 Actual Company\")",
            "formatString": "0.00",
            "lineageTag": "6ac31edd-1f18-46b6-b80d-3cd868531735"
          },
          {
            "name": "2021 % Value",
            "displayFolder": "Statements %",
            "expression": "CALCULATE(SUM('Fin Ratio 2023'[Value]), 'Fin Ratio 2023'[Report Date] = MAX('Fin Ratio 2023'[Report Date]), 'Fin Ratio 2023'[Attribute] = \"2021 Actual Group\" || 'Fin Ratio 2023'[Attribute] = \"2021 Actual Company\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7903f76d-edaf-410d-9c74-8a1ad0ed84ed"
          },
          {
            "name": "SelectedMonth",
            "displayFolder": "Statements %",
            "expression": "IF(ISFILTERED('Calendar Fin CFO'[MonthLong]), SELECTEDVALUE('Calendar Fin CFO'[MonthNo]), CALCULATE(MAX('Calendar Fin CFO'[MonthNo]), 'Calendar Fin CFO'[Report Date] = MAX('Calendar Fin CFO'[Report Date]))) ",
            "formatString": "0",
            "lineageTag": "133aa6ce-d33f-4d7a-8170-70b8f56c693d"
          },
          {
            "name": "TotalFreeCashFLow",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Cashflow",
            "expression": [
              "IF(ISFILTERED('Fin CFO Dashboard'[Entity]),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), LASTDATE('Fin CFO Dashboard'[Report Date]), 'Fin CFO Dashboard'[Items] = \"Total Free Cash Flow\"),",
              "CALCULATE(SUM('Fin CFO Dashboard'[Actual YTD/< 30 Days]), LASTDATE('Fin CFO Dashboard'[Report Date]), 'Fin CFO Dashboard'[Items] = \"Total Free Cash Flow\", 'Fin CFO Dashboard'[Entity] = \"Group\"))"
            ],
            "formatString": "#,0",
            "lineageTag": "d91d8eef-4c9b-47d3-a411-addbbcd7f0b4"
          },
          {
            "name": "SelectedItemsBar",
            "displayFolder": "Dynamic Titles",
            "expression": "COMBINEVALUES(\" \", SELECTEDVALUE(SortItems[Items]), \"of Actual YTD, Budgeted YTD, & Actual PY\") ",
            "lineageTag": "9154c3c7-b8a9-4065-b722-ebf07c9c89b0"
          },
          {
            "name": "SelectedItemsPie",
            "displayFolder": "Dynamic Titles",
            "expression": "COMBINEVALUES(\" \", SELECTEDVALUE(SortItems[Items]), \"of Actual YTD by Sectors\") ",
            "lineageTag": "5a622ab3-5bae-4c3b-800c-49e720418efa"
          },
          {
            "name": "SelectedItemsBudget",
            "displayFolder": "Dynamic Titles",
            "expression": "COMBINEVALUES(\" \", SELECTEDVALUE(SortItems[Items]), \"of Actual YTD vs Budgeted YTD\")",
            "lineageTag": "595c2ebf-2cb1-4bcf-ba83-6f529445e733"
          },
          {
            "name": "SelectedItemsPY",
            "displayFolder": "Dynamic Titles",
            "expression": "COMBINEVALUES(\" \", SELECTEDVALUE(SortItems[Items]), \"of Actual YTD vs Actual PY\")",
            "lineageTag": "ce8fd213-40b8-496c-824b-585bab20e8ec"
          }
        ],
        "partitions": [
          {
            "name": "Measure-65d61a9e-93c3-4869-b403-d66a888280e6",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "SortItems",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9d99584-b433-4437-81c1-6e8c613e8698",
            "sortByColumn": "Index",
            "sourceColumn": "Items",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "21be52fb-0dc5-49d2-a87b-4fa9713d2bb6",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0adf2c2c-8310-4893-8f6c-e2e250bb0d2d",
        "partitions": [
          {
            "name": "SortItems-a7b4e913-40f0-4311-8374-fdf7021d2785",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"TY7NDoIwEIRfpemZg7/xLCKJCVGi3JBDlY00lq1ui8S3t9JYvOxhZr6dKUteaCsUSwmAbYRpWKp0zyO+4FVU8kwCMnETEo1laeL05aB7KIGHNtJGHhRYs1jg3R0l8ArGped/6VgT6V7i7WtMB+PUCIJGqxro3E0ms5VhaYe182eDvwfrSi427MlJP4DsO3zY4kuSxhbQBupgG6CxPZPPTtZjJ7SSBc0TO6V+gmeO8ALsYKyJd0WyDvk8LkI0Xxd+XvUB\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Items = _t, Index = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Items\", type text}, {\"Index\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SortCategory",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe3e84d1-eb77-4d3d-a8b9-12de7ec9b730",
            "sortByColumn": "Index",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c3446031-cac2-4735-8394-33425c155234",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fc79b728-28d7-40ac-8a35-8efc6e10068f",
        "partitions": [
          {
            "name": "SortCategory-1b867239-91ae-4d9a-8c74-cc4c1cb719b9",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCkpNTs0sS0zKSS1W0lEyVIrViVYKKUpMSVUISKwECytEhrgApYzAUv4lGalFcCmgsLFSbCwA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Category = _t, Index = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Category\", type text}, {\"Index\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SortSector",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "984dd684-c459-43fa-b69d-63c9ce70f805",
            "sortByColumn": "Index",
            "sourceColumn": "Sector",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "01186414-8448-4483-9c4e-818c817684da",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "aa506d48-4a83-4365-9483-0d550bae5d67",
        "partitions": [
          {
            "name": "SortSector-61bdda89-ed51-4dc7-ab75-b51cb579ee8a",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCijKL0gtKqlU0lEyVIrViVZyzSvLLMrPy03NKwGKGYHFgIpKUpMzgHxjMN83Ma80LTG5pLQoMy8dKGoC1ZlalF6pEFNqYGBkphBakpmTWZKZWgyUNwXLe+aV6Sl45OekQDSZgQX9SzJSi4ohJscCAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Sector = _t, Index = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Index\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Aging",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d1477aa6537a47a6baad108bb1141a04"
          }
        ],
        "columns": [
          {
            "name": "Aging",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "e93129ed-15e2-4041-901d-0139e1b9fbd4",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Aging Fields"
                }
              ]
            },
            "sortByColumn": "Aging Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Aging Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "4a2b5e5f-bd68-4597-a2aa-449ac72320a7",
            "sortByColumn": "Aging Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Aging Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "ff18c4fb-606b-44bf-88a3-dcaaad26aca5",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "b098c832-9b43-4397-b6fa-12f01b4efe53",
        "partitions": [
          {
            "name": "Aging-14e93160-d876-42e5-95ea-4619eae57be6",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"< 30 Days\", NAMEOF('Measure'[<30Days]), 0),",
                "    (\"31-60 Days\", NAMEOF('Measure'[31-60Days]), 1),",
                "    (\"61-90 Days\", NAMEOF('Measure'[61-90Days]), 2),",
                "    (\"91-365 Days\", NAMEOF('Measure'[91-365Days]), 3),",
                "    (\"> 365 Days\", NAMEOF('Measure'[>365Days]), 4)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "SortCategory 2",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f1e9517-d55d-443e-b2bb-7aadada6729a",
            "sortByColumn": "Index",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d1bf470a-cb32-4e2c-bf22-a7366359ae5a",
            "sourceColumn": "Index",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "79fcf5fd-de79-46c4-aec5-da0937dc32a0",
        "partitions": [
          {
            "name": "SortCategory 2-c6dda6ea-fefb-4a48-9fb0-29cde9710297",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCkpNTs0sS0zKSS1W0lEyVIrViVYKSKyECRgpxcYCAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Category = _t, Index = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Category\", type text}, {\"Index\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "File and Date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "5732cf4b-aba0-4843-81bb-addce8f2ac0b",
            "sortByColumn": "Index",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1942d2d5-284b-4f22-9e12-c62d3f9856ce",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f505174c-9f82-45f9-bd3a-f7df7facc40c"
                },
                "isDefault": true,
                "relationship": "5a093866-b3c0-45f7-878c-a658aedaea84"
              }
            ]
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "61b1fe24-b069-4fbc-a446-098f539f8058",
            "sourceColumn": "Index",
            "summarizeBy": "sum"
          },
          {
            "name": "Date - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "33d5fe0b-1c7f-45b5-955d-53bee326034a",
            "sortByColumn": "Index",
            "sourceColumn": "Date - Copy",
            "summarizeBy": "none"
          },
          {
            "name": "Month Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "867e0bf5-0025-413c-9eb2-ea78b801ad69",
            "sortByColumn": "Index",
            "sourceColumn": "Month Short",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('File and Date'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "2c7682d9-5f24-47a1-b24c-48a74d0174de",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "7fc4bbdf-7fb8-4275-9a39-1c6708a93b0c",
        "measures": [
          {
            "name": "Year Display",
            "expression": [
              "",
              "Var A = SELECTEDVALUE('File and Date'[Year])",
              "Var B = IF(HASONEFILTER('File and Date'[Year])=TRUE, A,\"All Year\")",
              "",
              "return",
              "B"
            ],
            "formatString": "0",
            "lineageTag": "026b1b1b-d03e-489d-8f49-5d7c2cbfaf41"
          }
        ],
        "partitions": [
          {
            "name": "File and Date-c425ff0c-4c37-4315-8c40-a29a93d38cb4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"a33660ba-8e4f-4d2d-8832-c88dc75b942a\" = Workspaces{[workspaceId=\"a33660ba-8e4f-4d2d-8832-c88dc75b942a\"]}[Data],",
                "    #\"2a18ca18-6eb1-4769-9072-75fde30a237d\" = #\"a33660ba-8e4f-4d2d-8832-c88dc75b942a\"{[dataflowId=\"2a18ca18-6eb1-4769-9072-75fde30a237d\"]}[Data],",
                "    #\"File and Date_\" = #\"2a18ca18-6eb1-4769-9072-75fde30a237d\"{[entity=\"File and Date\",version=\"\"]}[Data],",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"File and Date_\", \"Date\", \"Date - Copy\"),",
                "    #\"Extracted Month Name\" = Table.TransformColumns(#\"Duplicated Column\", {{\"Date - Copy\", each Date.MonthName(_), type text}}),",
                "    #\"Inserted First Characters\" = Table.AddColumn(#\"Extracted Month Name\", \"Month Short\", each Text.Start([#\"Date - Copy\"], 3), type text)",
                "in",
                "    #\"Inserted First Characters\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_f505174c-9f82-45f9-bd3a-f7df7facc40c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a324b496-3922-4807-8f85-87b282633674",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ff66b04a-c9ed-4ff5-ba8b-7da57dfc6c43",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "30994dc8-73e3-4d85-b255-082a9e16a7e3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ac474972-537b-4b9e-b447-f443d4a04f0d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a87f479e-3883-4fe5-b3dc-2200cb6e7c52",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6749fbc7-03d1-4d00-8925-4579f466b52f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "71ae252f-6933-45a3-8319-bed2bd860f7e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d33a3698-7650-40e3-b5a6-21c7f43bb1de",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1ceaf440-cb91-459f-b9b8-b305263dfe6c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "68823e11-1274-44e7-a7da-eee19f442f8a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2e880683-33a3-44d5-9abd-d4f618911515",
                "ordinal": 3
              }
            ],
            "lineageTag": "6d57522f-1780-4462-9e02-8ca5b99c7685"
          }
        ],
        "isHidden": true,
        "lineageTag": "a6401777-02ec-4467-a737-793b7a452b6a",
        "partitions": [
          {
            "name": "LocalDateTable_f505174c-9f82-45f9-bd3a-f7df7facc40c-8fc32670-3c2f-4ca6-9424-64662d1063c9",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('File and Date'[Date])), 1, 1), Date(Year(MAX('File and Date'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Fin CFO Dashboard",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Entity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93efe0ca-7df6-435d-af56-c1b4f47c0c03",
            "sourceColumn": "Entity",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8dcfc4ca-a1e7-4052-b3e5-75d1a9e7219b",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Items Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "940e0200-99c4-4a99-a956-593e76e590a2",
            "sourceColumn": "Items Category",
            "summarizeBy": "none"
          },
          {
            "name": "Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbc02d32-d0b5-42c6-8d99-7bc9d49f483c",
            "sourceColumn": "Items",
            "summarizeBy": "none"
          },
          {
            "name": "Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48e55534-fe81-47fd-976e-2e6372ac6d95",
            "sourceColumn": "Sector",
            "summarizeBy": "none"
          },
          {
            "name": "Actual YTD/< 30 Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0b895529-65ef-4d56-a65d-a792e06a570d",
            "sourceColumn": "Actual YTD/< 30 Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Budget YTD/31 - 60 Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "79b4e742-c8ba-4041-abb3-80acd90afe33",
            "sourceColumn": "Budget YTD/31 - 60 Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Current Year Budget/61 - 90 Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "44a80ad9-ab3d-4a89-a9ce-4b06433000d7",
            "sourceColumn": "Current Year Budget/61 - 90 Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Next Year Budget/91 - 365 Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "49d69f4e-c489-4d19-b92a-d9dbcaf7b63e",
            "sourceColumn": "Next Year Budget/91 - 365 Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Previous Year Actual/> 365 Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "18b6b8d6-55bf-4e59-9479-164c04fd5006",
            "sourceColumn": "Previous Year Actual/> 365 Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Report Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "75d16724-1a4b-4758-b01b-f69f979b7304",
            "sourceColumn": "Report Date",
            "summarizeBy": "none"
          },
          {
            "name": "Total Aging",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "'Fin CFO Dashboard'[Actual YTD/< 30 Days]+",
              "'Fin CFO Dashboard'[Budget YTD/31 - 60 Days]+",
              "'Fin CFO Dashboard'[Current Year Budget/61 - 90 Days]+",
              "'Fin CFO Dashboard'[Next Year Budget/91 - 365 Days]+",
              "'Fin CFO Dashboard'[Previous Year Actual/> 365 Days]  "
            ],
            "isDataTypeInferred": true,
            "lineageTag": "36c906db-66b1-4266-9c1d-cf89b668c497",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "a9897faf-fb77-45e7-8f82-88778cec37ff",
        "partitions": [
          {
            "name": "Fin CFO Dashboard",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"a33660ba-8e4f-4d2d-8832-c88dc75b942a\" = Workspaces{[workspaceId=\"a33660ba-8e4f-4d2d-8832-c88dc75b942a\"]}[Data],",
                "    #\"86f09d58-00fb-496c-94de-96710cf5451c\" = #\"a33660ba-8e4f-4d2d-8832-c88dc75b942a\"{[dataflowId=\"86f09d58-00fb-496c-94de-96710cf5451c\"]}[Data],",
                "    #\"Fin CFO Dashboard_\" = #\"86f09d58-00fb-496c-94de-96710cf5451c\"{[entity=\"Fin CFO Dashboard\",version=\"\"]}[Data]",
                "in",
                "    #\"Fin CFO Dashboard_\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar Fin CFO",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "81a7e643c0354622ad4be90bb907f0aa"
          }
        ],
        "columns": [
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH('Calendar Fin CFO'[Report Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "e7d42937-92a7-4cd6-80b7-bdcc5fdc2f2d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Calendar Fin CFO'[Report Date], \"MMM\") ",
            "isDataTypeInferred": true,
            "lineageTag": "66398b0a-53b3-43e8-be3a-a3ad6787aa9b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QtrNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "QUARTER('Calendar Fin CFO'[Report Date]) ",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "d2e87b46-8891-40af-acdd-a898670c7748",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Qtr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "COMBINEVALUES(\" \", \"Qtr\", QUARTER('Calendar Fin CFO'[Report Date])) ",
            "isDataTypeInferred": true,
            "lineageTag": "21599ef1-c582-4d0f-b9e2-2bddeec046ba",
            "sortByColumn": "QtrNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('Calendar Fin CFO'[Report Date]) ",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "f2d2fee7-d56d-49fc-8233-a780f37aa3d0",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Report Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3ce7e1f2-7078-4256-8375-fcb0e4e957c0",
            "sourceColumn": "[Report Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_dbdee00c-5d5c-45f1-b3fd-cbe498e48cff"
                },
                "isDefault": true,
                "relationship": "69c183b0-04da-4daa-8bb2-b0ac6448270a"
              }
            ]
          },
          {
            "name": "MonthLong",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Calendar Fin CFO'[Report Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "c6b4cc69-11ab-4080-8b3a-e43ed7f9e8b6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "0be5c9fb-2a9a-4b8c-981a-25f703ef1e4e",
        "partitions": [
          {
            "name": "Calendar Fin CFO",
            "mode": "import",
            "source": {
              "expression": [
                "SUMMARIZE(UNION(",
                "    SELECTCOLUMNS('Fin CFO Dashboard', \"Report Date\", 'Fin CFO Dashboard'[Report Date]),",
                "    SELECTCOLUMNS('Fin Ratio 2023', \"Report Date\", 'Fin Ratio 2023'[Report Date])),",
                "    [Report Date]) "
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Fin Ratio 2023",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "527c4657-f423-47aa-8f0a-7251c6fdf043",
            "sourceColumn": "Items",
            "summarizeBy": "none"
          },
          {
            "name": "Report Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "779af436-9bf0-4762-aa20-ba62844a87e1",
            "sourceColumn": "Report Date",
            "summarizeBy": "none"
          },
          {
            "name": "Items Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96005909-e281-4a59-9108-52bbe59759c4",
            "sourceColumn": "Items Category",
            "summarizeBy": "none"
          },
          {
            "name": "Attribute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "553a5e77-8bac-4bb7-a791-79e0d33f0d06",
            "sourceColumn": "Attribute",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5ec6893a-8599-4929-ae17-965cf1dbc53e",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Entity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2769120d-daaa-47bf-86f8-82ef7748ac28",
            "sourceColumn": "Entity",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f5712635-6e97-4689-9663-5835256db140",
        "partitions": [
          {
            "name": "Fin Ratio 2023",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"a33660ba-8e4f-4d2d-8832-c88dc75b942a\" = Workspaces{[workspaceId=\"a33660ba-8e4f-4d2d-8832-c88dc75b942a\"]}[Data],",
                "    #\"86f09d58-00fb-496c-94de-96710cf5451c\" = #\"a33660ba-8e4f-4d2d-8832-c88dc75b942a\"{[dataflowId=\"86f09d58-00fb-496c-94de-96710cf5451c\"]}[Data],",
                "    #\"Fin Ratio 2023_\" = #\"86f09d58-00fb-496c-94de-96710cf5451c\"{[entity=\"Fin Ratio 2023\",version=\"\"]}[Data]",
                "in",
                "    #\"Fin Ratio 2023_\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_dbdee00c-5d5c-45f1-b3fd-cbe498e48cff",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1c7340a4-6296-4329-bc29-dade581c7c25",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "32a278f0-587c-46d2-9458-2301991539bd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "ed74473f-ad5d-406c-96c8-9b6f296ce45f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "75b0f1f0-727d-40a1-96e6-18076f8f37ed",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "379074c7-5ade-45f4-9ecb-10eabb3cff28",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "51587613-9b62-4020-9b54-81ba455981a2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "d4c9c06a-7cea-48c4-bac2-ae33217dfd9a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d6d2da36-50e8-47d8-84eb-7d26bbf94fd6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "18279695-7a06-46d1-8309-c19ee4d90c99",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "76619c61-3227-443a-9f96-81e43fe0764c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6c020512-a67e-4c29-ac6b-fb5d6adebf7a",
                "ordinal": 3
              }
            ],
            "lineageTag": "0f5d7295-9284-478d-9fbb-0c6448101237"
          }
        ],
        "isHidden": true,
        "lineageTag": "79a2a126-2dce-408d-891b-4deb9725561b",
        "partitions": [
          {
            "name": "LocalDateTable_dbdee00c-5d5c-45f1-b3fd-cbe498e48cff",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar Fin CFO'[Report Date])), 1, 1), Date(Year(MAX('Calendar Fin CFO'[Report Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Sort Ratio Items",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "73f316bb-10ed-4f68-9ccf-3e4e8ce3ddcb",
            "sortByColumn": "Index",
            "sourceColumn": "Items",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4cb221a2-3b46-4045-ba45-add72c65322b",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a1c7e902-4067-406d-8d2b-1c2be94bb0fd",
        "partitions": [
          {
            "name": "Sort Ratio Items",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"a33660ba-8e4f-4d2d-8832-c88dc75b942a\" = Workspaces{[workspaceId=\"a33660ba-8e4f-4d2d-8832-c88dc75b942a\"]}[Data],",
                "    #\"86f09d58-00fb-496c-94de-96710cf5451c\" = #\"a33660ba-8e4f-4d2d-8832-c88dc75b942a\"{[dataflowId=\"86f09d58-00fb-496c-94de-96710cf5451c\"]}[Data],",
                "    #\"Sort Ratio Items_\" = #\"86f09d58-00fb-496c-94de-96710cf5451c\"{[entity=\"Sort Ratio Items\",version=\"\"]}[Data]",
                "in",
                "    #\"Sort Ratio Items_\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "type of inv sort",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Type of Investment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "203e4589-b928-460a-b9f7-7d9f225bc03f",
            "sortByColumn": "No",
            "sourceColumn": "Type of Investment",
            "summarizeBy": "none"
          },
          {
            "name": "No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1e97bf9c-9a1e-4f3b-b8ad-dec91eb2150e",
            "sourceColumn": "No",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "3faf31fa-9c11-46a1-b163-84619c6a161a",
        "partitions": [
          {
            "name": "type of inv sort",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"a33660ba-8e4f-4d2d-8832-c88dc75b942a\" = Workspaces{[workspaceId=\"a33660ba-8e4f-4d2d-8832-c88dc75b942a\"]}[Data],",
                "    #\"2a18ca18-6eb1-4769-9072-75fde30a237d\" = #\"a33660ba-8e4f-4d2d-8832-c88dc75b942a\"{[dataflowId=\"2a18ca18-6eb1-4769-9072-75fde30a237d\"]}[Data],",
                "    #\"Lead (First Column)_\" = #\"2a18ca18-6eb1-4769-9072-75fde30a237d\"{[entity=\"Lead (First Column)\",version=\"\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Lead (First Column)_\",{\"Type of Investment\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Removed Duplicates\", \"No\", each if [Type of Investment] = \"Money Market (Cash & cash Equivalents)\" then 1 else if [Type of Investment] = \"Unit Trust Fund\" then 2 else if [Type of Investment] = \"Direct Investment\" then 3 else if [Type of Investment] = \"(Bond & Equity)\" then 4 else if [Type of Investment] = \"\" then 5 else null, type number)",
                "in",
                "    #\"Added Conditional Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Legal - Major Legal Exposure",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Case",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3486322c-b3aa-4bb6-b7f5-f8ea13db146d",
            "sourceColumn": "Case",
            "summarizeBy": "none"
          },
          {
            "name": "Parties Involved",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67e8ff91-d9b9-498a-ad14-56910b2b88e4",
            "sourceColumn": "Parties Involved",
            "summarizeBy": "none"
          },
          {
            "name": "Financial/Legal Implication (RM)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-MY\"}"
              }
            ],
            "dataType": "double",
            "formatString": "\"RM\"#,0;-\"RM\"#,0;\"RM\"#,0",
            "lineageTag": "7b17329b-5703-4221-bb6c-18b0c3816c41",
            "sourceColumn": "Financial/Legal Implication (RM)",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "593ca0af-48bc-48d2-a6a6-d2632e9e6e80",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "Next Hearing Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "dde9cfaf-f482-4b85-97fd-3c884991fb75",
            "sourceColumn": "Next Hearing Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f554ce51-35a6-4445-a2f3-e881cb9da01b"
                },
                "isDefault": true,
                "relationship": "8b1d6346-a41d-46ca-8570-54f30b04a3d6"
              }
            ]
          },
          {
            "name": "Outcome Prediction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1abfc66c-2a6b-4691-b283-18f564ce40eb",
            "sourceColumn": "Outcome Prediction",
            "summarizeBy": "none"
          },
          {
            "name": "Date Case Filed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f24d1a0f-6c0d-4669-b096-b2232354eb2d",
            "sourceColumn": "Date Case Filed",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e3c4b969-af3e-4562-9aca-fd58fbf576de"
                },
                "isDefault": true,
                "relationship": "ce0eb82b-f3d7-4488-bc81-b265b40e2f9f"
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "Next Hearing Date Hierarchy",
            "levels": [
              {
                "name": "Next Hearing Date",
                "column": "Next Hearing Date",
                "lineageTag": "2be33029-8650-461b-8d60-952073ffc113",
                "ordinal": 0
              }
            ],
            "lineageTag": "dbe5a551-8e57-43a3-a168-9381fff4edcd"
          }
        ],
        "lineageTag": "11061e6e-4498-4ee6-a615-e3ba18ca4509",
        "partitions": [
          {
            "name": "Legal - Major Legal Exposure",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = SharePoint.Tables(\"https://worldwideholdingsberhad.sharepoint.com/sites/GroupLegalDept/\", [Implementation=\"2.0\", ViewMode=\"All\"]),",
                "    #\"8d0927c6-140f-4cf1-8fd2-e7bc06f17c9d\" = Source{[Id=\"8d0927c6-140f-4cf1-8fd2-e7bc06f17c9d\"]}[Items],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"8d0927c6-140f-4cf1-8fd2-e7bc06f17c9d\",{\"Case\", \"Parties Involved\", \"Financial/Legal Implication (RM)\", \"Date Case Filed\", \"Status\", \"Next Hearing Date\", \"Outcome Prediction\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Other Columns\",{{\"Next Hearing Date\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_f554ce51-35a6-4445-a2f3-e881cb9da01b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e7d44816-38b7-4a55-bd87-fcf4799de08d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "919cbbbf-8359-4088-be43-bfd3c02f8f3d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "15441ef7-6358-41d0-b31d-3b6de7dcfdb6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e09f3390-f692-46ab-8c5e-131b561bb4c8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "fe9fb3e9-8bb0-45b9-a96a-8d14979820bd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a6e5dce9-69c2-4eff-9f0c-9fde111ecb3d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "f8defbea-d5cc-4204-a4c0-d70cd468121c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "e816cd49-8c6a-4773-b84e-6604cc9bb573",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1bea6323-4af9-40db-9764-9827cbddcc50",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0e9d67c5-ac06-4d20-abc7-1b9bfa029f7b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "5470f8c1-b5df-476d-92b5-9634cdb08206",
                "ordinal": 3
              }
            ],
            "lineageTag": "cc905dc6-ae24-4728-a75d-aeac871d9d87"
          }
        ],
        "isHidden": true,
        "lineageTag": "ccb0fa2d-af4e-4a50-959c-016c7d5f78ac",
        "partitions": [
          {
            "name": "LocalDateTable_f554ce51-35a6-4445-a2f3-e881cb9da01b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Legal - Major Legal Exposure'[Next Hearing Date])), 1, 1), Date(Year(MAX('Legal - Major Legal Exposure'[Next Hearing Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Project Team - Project Delivery",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Project",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f58fa99d-3a6f-4dd2-b184-8cc28880abee",
            "sourceColumn": "Project",
            "summarizeBy": "none"
          },
          {
            "name": "Project Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66dab68a-65a6-438f-b37a-2716729ab12e",
            "sourceColumn": "Project Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Planned Progress YTD (%)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a189ecd7-12cc-4613-8a56-4381c6d2eeb9",
            "sourceColumn": "Planned Progress YTD (%)",
            "summarizeBy": "none"
          },
          {
            "name": "Actual Progress YTD (%)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "40c4334a-8f8a-4e79-ae3b-b5e73d8f6971",
            "sourceColumn": "Actual Progress YTD (%)",
            "summarizeBy": "none"
          },
          {
            "name": "Target COD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "17430f49-16c2-42d4-b70b-3b36e0227b81",
            "sourceColumn": "Target COD",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_6c532078-52c3-4050-9403-1e5586b77d25"
                },
                "isDefault": true,
                "relationship": "f66dcef3-e510-4e5e-b7a6-20d2e3b21deb"
              }
            ]
          },
          {
            "name": "Revised COD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "04dca2a0-9751-4684-81ef-2a7ae8affa0a",
            "sourceColumn": "Revised COD",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_bdb843d8-8cdb-4dd9-aa55-7b0619d863a5"
                },
                "isDefault": true,
                "relationship": "7ab08032-3a88-4ec6-b11b-a520b6d9d153"
              }
            ]
          },
          {
            "name": "Next Critical Path",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd6768ff-e026-446e-ae70-8d0f0c74d7d0",
            "sourceColumn": "Next Critical Path",
            "summarizeBy": "none"
          },
          {
            "name": "Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "578c1e46-ec2d-4779-80c1-ddd559a834e7",
            "sourceColumn": "Comments",
            "summarizeBy": "none"
          },
          {
            "name": "Delay Calculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cc6a10e9-bff1-44f6-bda0-de3b04c82b58",
            "sourceColumn": "Delay Calculated",
            "summarizeBy": "none"
          },
          {
            "name": "Days Ahead of Schedule",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7d6896ad-a72f-44c1-b92c-19fa9098026b",
            "sourceColumn": "Days Ahead of Schedule",
            "summarizeBy": "none"
          },
          {
            "name": "Target COD vs Today",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2830367d-4393-4db7-92d4-f70feb372285",
            "sourceColumn": "Target COD vs Today",
            "summarizeBy": "sum"
          },
          {
            "name": "Notice to Proceed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8008e05b-fe3e-4c6d-8372-d5bedb6b28c4",
            "sourceColumn": "Notice to Proceed",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_4c8fda47-6501-4a3e-bdc4-012ddbbd5524"
                },
                "isDefault": true,
                "relationship": "b01202db-02ae-4f58-a0fc-5e6eb292ad8c"
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "Notice to Proceed Hierarchy (NTP)",
            "levels": [
              {
                "name": "Notice to Proceed",
                "column": "Notice to Proceed",
                "lineageTag": "8bc2812a-d7ae-41a2-845f-b4b5496285c4",
                "ordinal": 0
              }
            ],
            "lineageTag": "b187d5d3-c219-435a-8fc8-eedc30e6dcbf"
          }
        ],
        "lineageTag": "47c1bcbc-6bfe-4ab4-a358-17602a6d6dae",
        "partitions": [
          {
            "name": "Project Team - Project Delivery",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = SharePoint.Tables(\"https://worldwideholdingsberhad.sharepoint.com/cp/\", [Implementation=null, ApiVersion=15]),",
                "    #\"af4f6c85-25f9-4e5b-9ed8-863e6fd953e0\" = Source{[Id=\"af4f6c85-25f9-4e5b-9ed8-863e6fd953e0\"]}[Items],",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"af4f6c85-25f9-4e5b-9ed8-863e6fd953e0\",{{\"ID\", \"ID.1\"}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Renamed Columns\",{\"ProjectManager\", \"PlannedProgressYTD(%\", \"ActualProgressYTD(%_\", \"TargetCOD\", \"RevisedCOD(ifnorevision_x0\", \"NextCriticalPath\", \"Comments\", \"Prj\", \"Daysaheadofschedule[No_x00\", \"Delay Calculated\", \"NoticetoProceed\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"Prj\", \"Project\"}, {\"ProjectManager\", \"Project Manager\"}, {\"PlannedProgressYTD(%\", \"Planned Progress YTD (%)\"}, {\"ActualProgressYTD(%_\", \"Actual Progress YTD (%)\"}, {\"TargetCOD\", \"Target COD\"}, {\"RevisedCOD(ifnorevision_x0\", \"Revised COD (if no revision, key in Target COD)\"}, {\"NextCriticalPath\", \"Next Critical Path\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"Target COD\", type date}, {\"Revised COD (if no revision, key in Target COD)\", type date}, {\"Delay Calculated\", Percentage.Type}, {\"Planned Progress YTD (%)\", Percentage.Type}, {\"Actual Progress YTD (%)\", Percentage.Type}, {\"Daysaheadofschedule[No_x00\", Int64.Type}}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Changed Type\",{{\"Daysaheadofschedule[No_x00\", \"Days Ahead of Schedule\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns2\", \"Target COD vs Today\", each [#\"Revised COD (if no revision, key in Target COD)\"]-DateTime.Date(DateTime.LocalNow())),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Target COD vs Today\", Int64.Type}, {\"NoticetoProceed\", type date}}),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Changed Type1\",{{\"NoticetoProceed\", \"Notice to Proceed\"}, {\"Revised COD (if no revision, key in Target COD)\", \"Revised COD\"}})",
                "in",
                "    #\"Renamed Columns3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_6c532078-52c3-4050-9403-1e5586b77d25",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d2f1eccb-e0de-4d66-9ee2-83a06e56a15a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "018e4daa-ff67-41a6-a592-e46eb5f5f380",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "7e0f8146-3026-406a-80c6-bff8427d67e8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e5ec01dd-a655-46d9-92fa-87df6c878c43",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "fbcc1f53-8204-4ed1-85ab-2fc3deb5600d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "69fc556b-da72-45c3-99c4-6df0a6b02bdf",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "3c223b9d-a736-4f86-9d08-f49ce01c9919",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "41903113-07b3-40a8-b09d-1fe9c4d6037e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a29b4e3d-319b-4fce-8977-ff5794614a74",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7ce7a138-ad0c-405c-adb3-47a38b051f05",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ad5958f0-4118-40da-b178-5beb3f66c9e8",
                "ordinal": 3
              }
            ],
            "lineageTag": "25fde1ae-661d-402c-aac4-ce4f8d388705"
          }
        ],
        "isHidden": true,
        "lineageTag": "16efb014-05c5-43cc-87a3-0b2f3b268a69",
        "partitions": [
          {
            "name": "LocalDateTable_6c532078-52c3-4050-9403-1e5586b77d25",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Project Team - Project Delivery'[Target COD])), 1, 1), Date(Year(MAX('Project Team - Project Delivery'[Target COD])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_bdb843d8-8cdb-4dd9-aa55-7b0619d863a5",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "670c464c-1c5a-4c49-91c3-277818da8422",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "24ed8711-426b-4d06-9ee4-a55fa8f07749",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "16b71be8-3dc7-473a-8505-cc35a572ba18",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a9ffa3fd-9781-49b2-8de6-ccbff8abb35c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "b550fcf4-cbcf-4534-9316-1d7cc6c05b73",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1dd5a4d1-6722-47cf-9ff4-fe7b4eec3575",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "72daa924-80fa-42b4-9133-14058b0d034e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "11ecb538-7fbc-453b-bd8f-f2f7e190b92d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "01658872-cd1d-4bf2-90f2-67ce149b8e30",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8f04e0d2-9f05-4986-af5f-e9eb7bd6ea0e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "61641abf-d66d-47f0-af5a-f48e235d731a",
                "ordinal": 3
              }
            ],
            "lineageTag": "91aae517-4a29-462b-8176-42cdedf5bd7f"
          }
        ],
        "isHidden": true,
        "lineageTag": "992cbf98-1c56-47f6-b87a-6bcdf18fcb01",
        "partitions": [
          {
            "name": "LocalDateTable_bdb843d8-8cdb-4dd9-aa55-7b0619d863a5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Project Team - Project Delivery'[Revised COD])), 1, 1), Date(Year(MAX('Project Team - Project Delivery'[Revised COD])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e3c4b969-af3e-4562-9aca-fd58fbf576de",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f82b3671-e254-4005-af94-64a53bfeb5f0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "81e89700-d031-48b3-8701-d8e79555d2e0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "4a525f09-ad2a-400a-a5f6-df4d4c81bae8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "5064a17a-485c-4b50-8ae1-26e3636db6fc",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "93e79e34-3d17-4604-be88-5c7c37b3e3eb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0f0b2b5f-bd26-4173-82c9-0ca2c0444c9b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "1747092c-088a-4d4f-8bfc-96fd364a319c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "88f5f973-0094-4365-9f84-31ce890b7f66",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d9cdc355-15b8-4387-b817-2ec7897e51b8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "97c3fd6e-8f16-4b43-be02-70561b4932fc",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ae77f646-1cd2-4cfb-845c-fddcab28c90e",
                "ordinal": 3
              }
            ],
            "lineageTag": "e128c4ed-46fc-461b-96be-e958a6d00a0e"
          }
        ],
        "isHidden": true,
        "lineageTag": "76b00800-aba2-45b3-ab16-f8cd1b409e43",
        "partitions": [
          {
            "name": "LocalDateTable_e3c4b969-af3e-4562-9aca-fd58fbf576de",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Legal - Major Legal Exposure'[Date Case Filed])), 1, 1), Date(Year(MAX('Legal - Major Legal Exposure'[Date Case Filed])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_4c8fda47-6501-4a3e-bdc4-012ddbbd5524",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "edfe1511-6f10-4920-bb50-15095b88e6ce",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "a380c864-83e8-4bba-a765-8dad3b5b0c18",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "d7a5eefa-311c-4921-a429-7f4a4b5244dc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "724e6847-f76e-4d86-b18c-394445e668aa",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "b07cfef5-db01-48da-8a7d-9a176f90e672",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9fd2610f-f093-45b7-b3a8-75a171447f68",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "54effbb7-4c35-47e8-89b9-1a038526be1c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "029ed7ce-aab1-4ec6-ad67-80010ef096ad",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d10c4675-cd78-4c56-b121-e08b923619c5",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c33e0ad4-bb26-47b8-b5aa-4db8f3275a18",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "832fb94c-3258-423c-9b37-e3e12a2ad2db",
                "ordinal": 3
              }
            ],
            "lineageTag": "41032e0b-bf1e-48b7-9802-cadf0114b7c4"
          }
        ],
        "isHidden": true,
        "lineageTag": "1e4ba714-d5fa-4545-a632-687563f0755d",
        "partitions": [
          {
            "name": "LocalDateTable_4c8fda47-6501-4a3e-bdc4-012ddbbd5524",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Project Team - Project Delivery'[Notice to Proceed])), 1, 1), Date(Year(MAX('Project Team - Project Delivery'[Notice to Proceed])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}